/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListListNameRouteImport } from './routes/list.$listName'
import { Route as CardNameRouteImport } from './routes/card.$name'
import { Route as BuildListNameRouteImport } from './routes/build.$listName'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListListNameRoute = ListListNameRouteImport.update({
  id: '/list/$listName',
  path: '/list/$listName',
  getParentRoute: () => rootRouteImport,
} as any)
const CardNameRoute = CardNameRouteImport.update({
  id: '/card/$name',
  path: '/card/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildListNameRoute = BuildListNameRouteImport.update({
  id: '/build/$listName',
  path: '/build/$listName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lists': typeof ListsRoute
  '/settings': typeof SettingsRoute
  '/build/$listName': typeof BuildListNameRoute
  '/card/$name': typeof CardNameRoute
  '/list/$listName': typeof ListListNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lists': typeof ListsRoute
  '/settings': typeof SettingsRoute
  '/build/$listName': typeof BuildListNameRoute
  '/card/$name': typeof CardNameRoute
  '/list/$listName': typeof ListListNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lists': typeof ListsRoute
  '/settings': typeof SettingsRoute
  '/build/$listName': typeof BuildListNameRoute
  '/card/$name': typeof CardNameRoute
  '/list/$listName': typeof ListListNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lists'
    | '/settings'
    | '/build/$listName'
    | '/card/$name'
    | '/list/$listName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lists'
    | '/settings'
    | '/build/$listName'
    | '/card/$name'
    | '/list/$listName'
  id:
    | '__root__'
    | '/'
    | '/lists'
    | '/settings'
    | '/build/$listName'
    | '/card/$name'
    | '/list/$listName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListsRoute: typeof ListsRoute
  SettingsRoute: typeof SettingsRoute
  BuildListNameRoute: typeof BuildListNameRoute
  CardNameRoute: typeof CardNameRoute
  ListListNameRoute: typeof ListListNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$listName': {
      id: '/list/$listName'
      path: '/list/$listName'
      fullPath: '/list/$listName'
      preLoaderRoute: typeof ListListNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$name': {
      id: '/card/$name'
      path: '/card/$name'
      fullPath: '/card/$name'
      preLoaderRoute: typeof CardNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/$listName': {
      id: '/build/$listName'
      path: '/build/$listName'
      fullPath: '/build/$listName'
      preLoaderRoute: typeof BuildListNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListsRoute: ListsRoute,
  SettingsRoute: SettingsRoute,
  BuildListNameRoute: BuildListNameRoute,
  CardNameRoute: CardNameRoute,
  ListListNameRoute: ListListNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
