/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardNameRouteImport } from './routes/card.$name'
import { Route as ListListIdSlugRouteImport } from './routes/list.$listId.$slug'
import { Route as BuildListIdSlugRouteImport } from './routes/build.$listId.$slug'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardNameRoute = CardNameRouteImport.update({
  id: '/card/$name',
  path: '/card/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ListListIdSlugRoute = ListListIdSlugRouteImport.update({
  id: '/list/$listId/$slug',
  path: '/list/$listId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildListIdSlugRoute = BuildListIdSlugRouteImport.update({
  id: '/build/$listId/$slug',
  path: '/build/$listId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lists': typeof ListsRoute
  '/settings': typeof SettingsRoute
  '/card/$name': typeof CardNameRoute
  '/build/$listId/$slug': typeof BuildListIdSlugRoute
  '/list/$listId/$slug': typeof ListListIdSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lists': typeof ListsRoute
  '/settings': typeof SettingsRoute
  '/card/$name': typeof CardNameRoute
  '/build/$listId/$slug': typeof BuildListIdSlugRoute
  '/list/$listId/$slug': typeof ListListIdSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lists': typeof ListsRoute
  '/settings': typeof SettingsRoute
  '/card/$name': typeof CardNameRoute
  '/build/$listId/$slug': typeof BuildListIdSlugRoute
  '/list/$listId/$slug': typeof ListListIdSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lists'
    | '/settings'
    | '/card/$name'
    | '/build/$listId/$slug'
    | '/list/$listId/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lists'
    | '/settings'
    | '/card/$name'
    | '/build/$listId/$slug'
    | '/list/$listId/$slug'
  id:
    | '__root__'
    | '/'
    | '/lists'
    | '/settings'
    | '/card/$name'
    | '/build/$listId/$slug'
    | '/list/$listId/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListsRoute: typeof ListsRoute
  SettingsRoute: typeof SettingsRoute
  CardNameRoute: typeof CardNameRoute
  BuildListIdSlugRoute: typeof BuildListIdSlugRoute
  ListListIdSlugRoute: typeof ListListIdSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$name': {
      id: '/card/$name'
      path: '/card/$name'
      fullPath: '/card/$name'
      preLoaderRoute: typeof CardNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$listId/$slug': {
      id: '/list/$listId/$slug'
      path: '/list/$listId/$slug'
      fullPath: '/list/$listId/$slug'
      preLoaderRoute: typeof ListListIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/$listId/$slug': {
      id: '/build/$listId/$slug'
      path: '/build/$listId/$slug'
      fullPath: '/build/$listId/$slug'
      preLoaderRoute: typeof BuildListIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListsRoute: ListsRoute,
  SettingsRoute: SettingsRoute,
  CardNameRoute: CardNameRoute,
  BuildListIdSlugRoute: BuildListIdSlugRoute,
  ListListIdSlugRoute: ListListIdSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
