/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListListIdSlugRouteImport } from './routes/list.$listId.$slug'
import { Route as CardOracleIdNameRouteImport } from './routes/card.$oracleId.$name'
import { Route as BuildListIdSlugRouteImport } from './routes/build.$listId.$slug'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListListIdSlugRoute = ListListIdSlugRouteImport.update({
  id: '/list/$listId/$slug',
  path: '/list/$listId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CardOracleIdNameRoute = CardOracleIdNameRouteImport.update({
  id: '/card/$oracleId/$name',
  path: '/card/$oracleId/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildListIdSlugRoute = BuildListIdSlugRouteImport.update({
  id: '/build/$listId/$slug',
  path: '/build/$listId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/build/$listId/$slug': typeof BuildListIdSlugRoute
  '/card/$oracleId/$name': typeof CardOracleIdNameRoute
  '/list/$listId/$slug': typeof ListListIdSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/build/$listId/$slug': typeof BuildListIdSlugRoute
  '/card/$oracleId/$name': typeof CardOracleIdNameRoute
  '/list/$listId/$slug': typeof ListListIdSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/build/$listId/$slug': typeof BuildListIdSlugRoute
  '/card/$oracleId/$name': typeof CardOracleIdNameRoute
  '/list/$listId/$slug': typeof ListListIdSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/lists'
    | '/login'
    | '/settings'
    | '/build/$listId/$slug'
    | '/card/$oracleId/$name'
    | '/list/$listId/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/lists'
    | '/login'
    | '/settings'
    | '/build/$listId/$slug'
    | '/card/$oracleId/$name'
    | '/list/$listId/$slug'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/lists'
    | '/login'
    | '/settings'
    | '/build/$listId/$slug'
    | '/card/$oracleId/$name'
    | '/list/$listId/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ListsRoute: typeof ListsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  BuildListIdSlugRoute: typeof BuildListIdSlugRoute
  CardOracleIdNameRoute: typeof CardOracleIdNameRoute
  ListListIdSlugRoute: typeof ListListIdSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$listId/$slug': {
      id: '/list/$listId/$slug'
      path: '/list/$listId/$slug'
      fullPath: '/list/$listId/$slug'
      preLoaderRoute: typeof ListListIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$oracleId/$name': {
      id: '/card/$oracleId/$name'
      path: '/card/$oracleId/$name'
      fullPath: '/card/$oracleId/$name'
      preLoaderRoute: typeof CardOracleIdNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/$listId/$slug': {
      id: '/build/$listId/$slug'
      path: '/build/$listId/$slug'
      fullPath: '/build/$listId/$slug'
      preLoaderRoute: typeof BuildListIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ListsRoute: ListsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  BuildListIdSlugRoute: BuildListIdSlugRoute,
  CardOracleIdNameRoute: CardOracleIdNameRoute,
  ListListIdSlugRoute: ListListIdSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
