/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as StoresSlugRouteImport } from './routes/stores.$slug'
import { Route as ListListNameRouteImport } from './routes/list.$listName'
import { Route as CardNameRouteImport } from './routes/card.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresSlugRoute = StoresSlugRouteImport.update({
  id: '/stores/$slug',
  path: '/stores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListListNameRoute = ListListNameRouteImport.update({
  id: '/list/$listName',
  path: '/list/$listName',
  getParentRoute: () => rootRouteImport,
} as any)
const CardNameRoute = CardNameRouteImport.update({
  id: '/card/$name',
  path: '/card/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stores': typeof StoresRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/card/$name': typeof CardNameRoute
  '/list/$listName': typeof ListListNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stores': typeof StoresRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/card/$name': typeof CardNameRoute
  '/list/$listName': typeof ListListNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stores': typeof StoresRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/card/$name': typeof CardNameRoute
  '/list/$listName': typeof ListListNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stores' | '/stores/$slug' | '/card/$name' | '/list/$listName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stores' | '/stores/$slug' | '/card/$name' | '/list/$listName'
  id: '__root__' | '/' | '/stores' | '/stores/$slug' | '/card/$name' | '/list/$listName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoresRoute: typeof StoresRoute
  StoresSlugRoute: typeof StoresSlugRoute
  CardNameRoute: typeof CardNameRoute
  ListListNameRoute: typeof ListListNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$slug': {
      id: '/stores/$slug'
      path: '/stores/$slug'
      fullPath: '/stores/$slug'
      preLoaderRoute: typeof StoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$listName': {
      id: '/list/$listName'
      path: '/list/$listName'
      fullPath: '/list/$listName'
      preLoaderRoute: typeof ListListNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$name': {
      id: '/card/$name'
      path: '/card/$name'
      fullPath: '/card/$name'
      preLoaderRoute: typeof CardNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoresRoute: StoresRoute,
  StoresSlugRoute: StoresSlugRoute,
  CardNameRoute: CardNameRoute,
  ListListNameRoute: ListListNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
