/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListListNameRouteImport } from './routes/list.$listName'
import { Route as CardNameRouteImport } from './routes/card.$name'

const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListListNameRoute = ListListNameRouteImport.update({
  id: '/list/$listName',
  path: '/list/$listName',
  getParentRoute: () => rootRouteImport,
} as any)
const CardNameRoute = CardNameRouteImport.update({
  id: '/card/$name',
  path: '/card/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tokens': typeof TokensRoute
  '/card/$name': typeof CardNameRoute
  '/list/$listName': typeof ListListNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tokens': typeof TokensRoute
  '/card/$name': typeof CardNameRoute
  '/list/$listName': typeof ListListNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tokens': typeof TokensRoute
  '/card/$name': typeof CardNameRoute
  '/list/$listName': typeof ListListNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tokens' | '/card/$name' | '/list/$listName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tokens' | '/card/$name' | '/list/$listName'
  id: '__root__' | '/' | '/tokens' | '/card/$name' | '/list/$listName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TokensRoute: typeof TokensRoute
  CardNameRoute: typeof CardNameRoute
  ListListNameRoute: typeof ListListNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$listName': {
      id: '/list/$listName'
      path: '/list/$listName'
      fullPath: '/list/$listName'
      preLoaderRoute: typeof ListListNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$name': {
      id: '/card/$name'
      path: '/card/$name'
      fullPath: '/card/$name'
      preLoaderRoute: typeof CardNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TokensRoute: TokensRoute,
  CardNameRoute: CardNameRoute,
  ListListNameRoute: ListListNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
