/**
 * Top 1000 most popular Magic: The Gathering cards
 *
 * Curated list of cards popular across formats:
 * - Commander/EDH staples
 * - Modern format staples
 * - Legacy format staples
 * - Pioneer format staples
 * - Standard format staples
 * - Highly sought-after collectibles
 */
export const POPULAR_CARDS = [
  // Power 9
  'Black Lotus',
  'Mox Sapphire',
  'Mox Jet',
  'Mox Ruby',
  'Mox Pearl',
  'Mox Emerald',
  'Time Walk',
  'Ancestral Recall',
  'Timetwister',

  // Top Commander Staples
  'Sol Ring',
  'Command Tower',
  'Arcane Signet',
  'Lightning Greaves',
  'Swiftfoot Boots',
  'Rhystic Study',
  'Smothering Tithe',
  'Cyclonic Rift',
  'Heroic Intervention',
  'Beast Within',
  'Swords to Plowshares',
  'Path to Exile',
  'Generous Gift',
  'Chaos Warp',
  'Return of the Wildspeaker',
  'Teferi\'s Protection',
  'Boros Charm',
  'Assassin\'s Trophy',
  'Anguished Unmaking',
  'Despark',
  'Terminate',
  'Vindicate',
  'Abrupt Decay',
  'Mortify',
  'Drown in the Loch',
  'Counterspell',
  'Swan Song',
  'Negate',
  'Arcane Denial',
  'Mana Drain',
  'Force of Will',
  'Force of Negation',
  'Pact of Negation',
  'Fierce Guardianship',
  'Deflecting Swat',
  'Dovin\'s Veto',
  'Krosan Grip',
  'Nature\'s Lore',
  'Three Visits',
  'Kodama\'s Reach',
  'Cultivate',
  'Rampant Growth',
  'Farseek',
  'Explosive Vegetation',
  'Skyshroud Claim',
  'Tempt with Discovery',
  'Worldly Tutor',
  'Vampiric Tutor',
  'Demonic Tutor',
  'Mystical Tutor',
  'Enlightened Tutor',
  'Gamble',
  'Imperial Seal',
  'Grim Tutor',
  'Merchant Scroll',
  'Dark Petition',

  // Card Draw
  'Rhystic Study',
  'Mystic Remora',
  'Sylvan Library',
  'Necropotence',
  'Phyrexian Arena',
  'The One Ring',
  'Esper Sentinel',
  'Ghostly Pilferer',
  'Trouble in Pairs',
  'Consecrated Sphinx',
  'Psychosis Crawler',
  'Blue Sun\'s Zenith',
  'Pull from Tomorrow',
  'Sphinx\'s Revelation',
  'Brainstorm',
  'Ponder',
  'Preordain',
  'Serum Visions',
  'Opt',
  'Consider',
  'Faithless Looting',
  'Night\'s Whisper',
  'Sign in Blood',
  'Read the Bones',
  'Ancient Craving',
  'Painful Truths',
  'Promise of Power',

  // Fetchlands
  'Scalding Tarn',
  'Misty Rainforest',
  'Verdant Catacombs',
  'Arid Mesa',
  'Marsh Flats',
  'Flooded Strand',
  'Polluted Delta',
  'Bloodstained Mire',
  'Wooded Foothills',
  'Windswept Heath',
  'Prismatic Vista',
  'Fabled Passage',
  'Evolving Wilds',
  'Terramorphic Expanse',

  // Shocklands
  'Steam Vents',
  'Hallowed Fountain',
  'Watery Grave',
  'Overgrown Tomb',
  'Sacred Foundry',
  'Breeding Pool',
  'Godless Shrine',
  'Stomping Ground',
  'Temple Garden',
  'Blood Crypt',

  // Triomes
  'Ketria Triome',
  'Indatha Triome',
  'Raugrin Triome',
  'Savai Triome',
  'Zagoth Triome',
  'Spara\'s Headquarters',
  'Raffine\'s Tower',
  'Xander\'s Lounge',
  'Ziatora\'s Proving Ground',
  'Jetmir\'s Garden',

  // Pain Lands
  'Adarkar Wastes',
  'Brushland',
  'Caves of Koilos',
  'Karplusan Forest',
  'Sulfurous Springs',
  'Underground River',
  'Llanowar Wastes',
  'Shivan Reef',
  'Yavimaya Coast',
  'Battlefield Forge',

  // Fast Lands
  'Spirebluff Canal',
  'Botanical Sanctum',
  'Concealed Courtyard',
  'Inspiring Vantage',
  'Blooming Marsh',
  'Blackcleave Cliffs',
  'Copperline Gorge',
  'Darkslick Shores',
  'Razorverge Thicket',
  'Seachrome Coast',

  // Check Lands
  'Glacial Fortress',
  'Drowned Catacomb',
  'Dragonskull Summit',
  'Rootbound Crag',
  'Sunpetal Grove',
  'Hinterland Harbor',
  'Sulfur Falls',
  'Woodland Cemetery',
  'Clifftop Retreat',
  'Isolated Chapel',

  // Filter Lands
  'Cascade Bluffs',
  'Fetid Heath',
  'Fire-Lit Thicket',
  'Flooded Grove',
  'Graven Cairns',
  'Mystic Gate',
  'Rugged Prairie',
  'Sunken Ruins',
  'Twilight Mire',
  'Wooded Bastion',

  // Bounce Lands
  'Azorius Chancery',
  'Dimir Aqueduct',
  'Rakdos Carnarium',
  'Gruul Turf',
  'Selesnya Sanctuary',
  'Orzhov Basilica',
  'Izzet Boilerworks',
  'Golgari Rot Farm',
  'Boros Garrison',
  'Simic Growth Chamber',

  // Utility Lands
  'Urborg, Tomb of Yawgmoth',
  'Cabal Coffers',
  'Nykthos, Shrine to Nyx',
  'Gaea\'s Cradle',
  'Ancient Tomb',
  'City of Traitors',
  'Cavern of Souls',
  'Boseiju, Who Endures',
  'Otawara, Soaring City',
  'Eiganjo, Seat of the Empire',
  'Sokenzan, Crucible of Defiance',
  'Takenuma, Abandoned Mire',
  'Bojuka Bog',
  'Reliquary Tower',
  'Mystic Sanctuary',
  'Castle Ardenvale',
  'Castle Vantress',
  'Castle Locthwain',
  'Castle Embereth',
  'Castle Garenbrig',
  'War Room',
  'Arch of Orazca',
  'Rogue\'s Passage',
  'Maze of Ith',
  'Thespian\'s Stage',
  'Vesuva',
  'Dark Depths',
  'Strip Mine',
  'Wasteland',
  'Ghost Quarter',
  'Field of Ruin',
  'Scavenger Grounds',

  // Mana Rocks
  'Sol Ring',
  'Mana Crypt',
  'Mana Vault',
  'Chrome Mox',
  'Mox Diamond',
  'Mox Opal',
  'Lion\'s Eye Diamond',
  'Lotus Petal',
  'Arcane Signet',
  'Fellwar Stone',
  'Mind Stone',
  'Thought Vessel',
  'Everflowing Chalice',
  'Talisman of Dominance',
  'Talisman of Indulgence',
  'Talisman of Impulse',
  'Talisman of Unity',
  'Talisman of Progress',
  'Talisman of Hierarchy',
  'Talisman of Creativity',
  'Talisman of Resilience',
  'Talisman of Conviction',
  'Talisman of Curiosity',
  'Signets',
  'Azorius Signet',
  'Dimir Signet',
  'Rakdos Signet',
  'Gruul Signet',
  'Selesnya Signet',
  'Orzhov Signet',
  'Izzet Signet',
  'Golgari Signet',
  'Boros Signet',
  'Simic Signet',
  'Worn Powerstone',
  'Thran Dynamo',
  'Gilded Lotus',
  'Chromatic Lantern',
  'Coalition Relic',
  'Coldsteel Heart',
  'Prismatic Lens',
  'Guardian Idol',
  'Basalt Monolith',
  'Grim Monolith',
  'The Celestus',
  'Replicating Ring',

  // Popular Creatures
  'Birds of Paradise',
  'Noble Hierarch',
  'Llanowar Elves',
  'Elvish Mystic',
  'Fyndhorn Elves',
  'Deathrite Shaman',
  'Ignoble Hierarch',
  'Avacyn\'s Pilgrim',
  'Arbor Elf',
  'Snapcaster Mage',
  'Dark Confidant',
  'Tarmogoyf',
  'Ragavan, Nimble Pilferer',
  'Esper Sentinel',
  'Dauthi Voidwalker',
  'Grief',
  'Fury',
  'Endurance',
  'Solitude',
  'Subtlety',
  'Dragon\'s Rage Channeler',
  'Ledger Shredder',
  'Monastery Swiftspear',
  'Delver of Secrets',
  'Young Pyromancer',
  'Thalia, Guardian of Thraben',
  'Stoneforge Mystic',
  'Collector Ouphe',
  'Scavenging Ooze',
  'Endurance',
  'Eternal Witness',
  'Ramunap Excavator',
  'Azusa, Lost but Seeking',
  'Oracle of Mul Daya',
  'Courser of Kruphix',
  'Tireless Tracker',
  'Risen Reef',
  'Omnath, Locus of Creation',
  'Golos, Tireless Pilgrim',
  'Korvold, Fae-Cursed King',
  'Kinnan, Bonder Prodigy',
  'Kess, Dissident Mage',
  'Muldrotha, the Gravetide',
  'Chulane, Teller of Tales',
  'Uro, Titan of Nature\'s Wrath',
  'Kroxa, Titan of Death\'s Hunger',
  'Primeval Titan',
  'Titan of Industry',
  'Inferno Titan',
  'Sun Titan',
  'Grave Titan',
  'Frost Titan',
  'Sheoldred, the Apocalypse',
  'Sheoldred, Whispering One',
  'Jin-Gitaxias, Progress Tyrant',
  'Vorinclex, Monstrous Raider',
  'Elesh Norn, Grand Cenobite',
  'Elesh Norn, Mother of Machines',
  'Atraxa, Praetors\' Voice',
  'Atraxa, Grand Unifier',
  'Avacyn, Angel of Hope',
  'Wurmcoil Engine',
  'Blightsteel Colossus',
  'Emrakul, the Aeons Torn',
  'Emrakul, the Promised End',
  'Ulamog, the Ceaseless Hunger',
  'Kozilek, Butcher of Truth',

  // Planeswalkers
  'Jace, the Mind Sculptor',
  'Liliana of the Veil',
  'Teferi, Time Raveler',
  'Teferi, Hero of Dominaria',
  'Wrenn and Six',
  'Oko, Thief of Crowns',
  'The Wandering Emperor',
  'Karn Liberated',
  'Ugin, the Spirit Dragon',
  'Ugin, the Ineffable',
  'Nicol Bolas, Dragon-God',
  'Nicol Bolas, the Ravager',
  'Nissa, Who Shakes the World',
  'Chandra, Torch of Defiance',
  'Gideon, Ally of Zendikar',
  'Elspeth, Sun\'s Champion',
  'Sorin, Imperious Bloodlord',
  'Narset, Parter of Veils',
  'Teferi, Master of Time',
  'Garruk Wildspeaker',
  'Vivien Reid',
  'Kaya, Ghost Assassin',
  'Ashiok, Dream Render',
  'Tamiyo, the Moon Sage',
  'Tezzeret, Agent of Bolas',
  'Saheeli Rai',
  'Dack Fayden',
  'Karn, the Great Creator',
  'Sarkhan, Fireblood',
  'Domri, Anarch of Bolas',
  'Vraska, Golgari Queen',
  'Ajani, Mentor of Heroes',
  'Nahiri, the Harbinger',
  'Minsc & Boo, Timeless Heroes',
  'Kaito Shizuki',
  'Wandering Emperor',

  // Combo Pieces
  'Thassa\'s Oracle',
  'Underworld Breach',
  'Dramatic Reversal',
  'Isochron Scepter',
  'Splinter Twin',
  'Deceiver Exarch',
  'Kiki-Jiki, Mirror Breaker',
  'Pestermite',
  'Devoted Druid',
  'Vizier of Remedies',
  'Walking Ballista',
  'Heliod, Sun-Crowned',
  'Spike Feeder',
  'Scurry Oak',
  'Crackle with Power',
  'Grapeshot',
  'Tendrils of Agony',
  'Aetherflux Reservoir',
  'Sanguine Bond',
  'Exquisite Blood',
  'Pestilence',
  'Aether Snap',
  'Ad Nauseam',
  'Angel\'s Grace',
  'Worldgorger Dragon',
  'Animate Dead',
  'Dance of the Dead',
  'Necromancy',
  'Dockside Extortionist',
  'Temur Sabertooth',
  'Cloudstone Curio',
  'Palinchron',
  'Deadeye Navigator',

  // Board Wipes
  'Wrath of God',
  'Day of Judgment',
  'Damnation',
  'Supreme Verdict',
  'Cyclonic Rift',
  'Toxic Deluge',
  'Blasphemous Act',
  'Austere Command',
  'Merciless Eviction',
  'Farewell',
  'Vanquish the Horde',
  'Devastation Tide',
  'Crux of Fate',
  'In Garruk\'s Wake',
  'Decree of Pain',
  'Hour of Revelation',
  'Terminus',
  'Hallowed Burial',
  'Cleansing Nova',
  'Winds of Abandon',
  'Settle the Wreckage',
  'Rout',
  'Fumigate',
  'Kaya\'s Wrath',

  // Equipment
  'Lightning Greaves',
  'Swiftfoot Boots',
  'Sword of Fire and Ice',
  'Sword of Feast and Famine',
  'Sword of Light and Shadow',
  'Sword of War and Peace',
  'Sword of Body and Mind',
  'Sword of Truth and Justice',
  'Sword of Sinew and Steel',
  'Sword of Hearth and Home',
  'Umezawa\'s Jitte',
  'Batterskull',
  'Skullclamp',
  'Sensei\'s Divining Top',
  'Scroll Rack',
  'Mystic Forge',
  'The One Ring',
  'Embercleave',
  'Shadowspear',
  'Esika\'s Chariot',
  'Godsend',
  'Argentum Armor',
  'Sunforger',
  'Helm of the Host',
  'Blackblade Reforged',
  'Stoneforge Masterwork',

  // Enchantments
  'Rhystic Study',
  'Smothering Tithe',
  'Sylvan Library',
  'Necropotence',
  'Phyrexian Arena',
  'Survival of the Fittest',
  'Oath of Druids',
  'Sneak Attack',
  'Show and Tell',
  'Omniscience',
  'Sterling Grove',
  'Privileged Position',
  'Greater Auramancy',
  'Land Tax',
  'Carpet of Flowers',
  'Burgeoning',
  'Exploration',
  'Parallel Lives',
  'Doubling Season',
  'Anointed Procession',
  'Cathars\' Crusade',
  'Impact Tremors',
  'Warstorm Surge',
  'Where Ancients Tread',
  'Gratuitous Violence',
  'Grave Pact',
  'Dictate of Erebos',
  'Black Market',
  'Animate Dead',
  'Reanimate',
  'Necromancy',
  'Dance of the Dead',

  // Artifacts
  'Sol Ring',
  'Mana Crypt',
  'Mox Opal',
  'Chrome Mox',
  'Sensei\'s Divining Top',
  'Scroll Rack',
  'The One Ring',
  'Aetherflux Reservoir',
  'Bolas\'s Citadel',
  'Crucible of Worlds',
  'Expedition Map',
  'Rings of Brighthearth',
  'Lithoform Engine',
  'Panharmonicon',
  'Strionic Resonator',
  'Altar of Dementia',
  'Ashnod\'s Altar',
  'Phyrexian Altar',
  'Krark-Clan Ironworks',
  'Birthing Pod',
  'Time Sieve',
  'Ichor Wellspring',
  'Spine of Ish Sah',
  'Wurmcoil Engine',
  'Solemn Simulacrum',
  'Meteor Golem',
  'Myr Battlesphere',

  // Instants & Sorceries - Removal
  'Lightning Bolt',
  'Fatal Push',
  'Abrupt Decay',
  'Assassin\'s Trophy',
  'Terminate',
  'Dreadbore',
  'Hero\'s Downfall',
  'Doom Blade',
  'Go for the Throat',
  'Murder',
  'Murderous Rider',
  'Bloodchief\'s Thirst',
  'Dismember',
  'Deadly Rollick',
  'Slaughter Pact',
  'Snuff Out',
  'Toxic Deluge',
  'Black Sun\'s Zenith',
  'Ratchet Bomb',
  'Engineered Explosives',
  'Detention Sphere',
  'Oblivion Ring',
  'Banishing Light',
  'Cast Out',
  'Grasp of Fate',
  'Council\'s Judgment',
  'Declaration in Stone',

  // Protection
  'Teferi\'s Protection',
  'Heroic Intervention',
  'Boros Charm',
  'Flawless Maneuver',
  'Eerie Interlude',
  'Ghostway',
  'Wrap in Vigor',
  'Unbreakable Formation',
  'Make a Stand',
  'Rootborn Defenses',
  'Clever Concealment',

  // Draw Spells
  'Blue Sun\'s Zenith',
  'Stroke of Genius',
  'Pull from Tomorrow',
  'Sphinx\'s Revelation',
  'Fact or Fiction',
  'Dig Through Time',
  'Treasure Cruise',
  'Thirst for Knowledge',
  'Impulse',
  'Chart a Course',
  'Frantic Search',
  'Deep Analysis',
  'Careful Study',
  'Thoughtcast',
  'Thought Scour',
  'Mental Note',

  // Tutors
  'Demonic Tutor',
  'Vampiric Tutor',
  'Imperial Seal',
  'Grim Tutor',
  'Diabolic Intent',
  'Diabolic Tutor',
  'Dark Petition',
  'Mastermind\'s Acquisition',
  'Beseech the Queen',
  'Increasing Ambition',
  'Scheming Symmetry',
  'Wishclaw Talisman',
  'Mystical Tutor',
  'Merchant Scroll',
  'Personal Tutor',
  'Worldly Tutor',
  'Sylvan Tutor',
  'Eladamri\'s Call',
  'Chord of Calling',
  'Green Sun\'s Zenith',
  'Finale of Devastation',
  'Congregation at Dawn',
  'Enlightened Tutor',
  'Idyllic Tutor',
  'Open the Armory',
  'Steelshaper\'s Gift',
  'Entomb',
  'Buried Alive',
  'Jarad\'s Orders',

  // Extra Turns
  'Time Warp',
  'Temporal Manipulation',
  'Capture of Jingzhou',
  'Temporal Trespass',
  'Part the Waterveil',
  'Nexus of Fate',
  'Alrund\'s Epiphany',
  'Karn\'s Temporal Sundering',

  // Reanimation
  'Reanimate',
  'Animate Dead',
  'Necromancy',
  'Dance of the Dead',
  'Living Death',
  'Victimize',
  'Dread Return',
  'Corpse Dance',
  'Unburial Rites',
  'Karmic Guide',
  'Reveillark',
  'Sun Titan',
  'Phyrexian Delver',
  'Body Snatcher',

  // Graveyard Hate
  'Rest in Peace',
  'Leyline of the Void',
  'Grafdigger\'s Cage',
  'Tormod\'s Crypt',
  'Relic of Progenitus',
  'Soul-Guide Lantern',
  'Scavenging Ooze',
  'Deathrite Shaman',
  'Scavenger Grounds',
  'Bojuka Bog',

  // Token Generators
  'Avenger of Zendikar',
  'Craterhoof Behemoth',
  'Hornet Queen',
  'Tendershoot Dryad',
  'Deep Forest Hermit',
  'Mycoloth',
  'Dragonmaster Outcast',
  'Dragon Broodmother',
  'Wurmcalling',
  'Secure the Wastes',
  'White Sun\'s Zenith',
  'March of the Multitudes',
  'Bitterblossom',
  'Grave Titan',

  // Dragons
  'Scion of the Ur-Dragon',
  'The Ur-Dragon',
  'Tiamat',
  'Ancient Gold Dragon',
  'Ancient Copper Dragon',
  'Ancient Silver Dragon',
  'Ancient Bronze Dragon',
  'Ancient Brass Dragon',
  'Dragonlord Dromoka',
  'Dragonlord Ojutai',
  'Dragonlord Silumgar',
  'Dragonlord Atarka',
  'Dragonlord Kolaghan',
  'Utvara Hellkite',
  'Scourge of Valkas',
  'Dragon Tempest',
  'Dragonstorm',
  'Lathliss, Dragon Queen',
  'Karrthus, Tyrant of Jund',
  'Nicol Bolas',
  'Bladewing the Risen',

  // Angels
  'Avacyn, Angel of Hope',
  'Lyra Dawnbringer',
  'Baneslayer Angel',
  'Resplendent Angel',
  'Angel of Serenity',
  'Platinum Angel',
  'Akroma, Angel of Wrath',
  'Akroma, Vision of Ixidor',
  'Aurelia, the Warleader',
  'Gisela, Blade of Goldnight',
  'Bruna, the Fading Light',
  'Gisela, the Broken Blade',
  'Sigarda, Host of Herons',
  'Linvala, Keeper of Silence',
  'Iona, Shield of Emeria',

  // Demons
  'Razaketh, the Foulblooded',
  'Rune-Scarred Demon',
  'Archfiend of Despair',
  'Vilis, Broker of Blood',
  'Massacre Wurm',
  'Demon of Dark Schemes',
  'Pestilence Demon',
  'Reaper from the Abyss',
  'Shadowborn Demon',
  'Harvester of Souls',

  // Elves
  'Elvish Archdruid',
  'Ezuri, Renegade Leader',
  'Priest of Titania',
  'Wirewood Symbiote',
  'Quirion Ranger',
  'Heritage Druid',
  'Nettle Sentinel',
  'Wirewood Lodge',
  'Gaea\'s Cradle',
  'Craterhoof Behemoth',
  'Chord of Calling',
  'Collected Company',
  'Lead the Stampede',

  // Goblins
  'Goblin Guide',
  'Goblin Chieftain',
  'Goblin Warchief',
  'Goblin Ringleader',
  'Goblin Matron',
  'Skirk Prospector',
  'Mogg War Marshal',
  'Munitions Expert',
  'Krenko, Mob Boss',
  'Krenko, Tin Street Kingpin',
  'Muxus, Goblin Grandee',
  'Rundvelt Hordemaster',

  // Humans
  'Thalia, Guardian of Thraben',
  'Champion of the Parish',
  'Mantis Rider',
  'Meddling Mage',
  'Reflector Mage',
  'Thalia\'s Lieutenant',
  'Kudro, Pride of Femeref',
  'General Kudro of Drannith',
  'Jirina Kudro',

  // Artifact/Affinity
  'Mox Opal',
  'Ornithopter',
  'Springleaf Drum',
  'Frogmite',
  'Myr Enforcer',
  'Thoughtcast',
  'Cranial Plating',
  'Arcbound Ravager',
  'Steel Overseer',
  'Master of Etherium',
  'Etched Champion',
  'Vault Skirge',
  'Signal Pest',

  // Storm
  'Tendrils of Agony',
  'Grapeshot',
  'Empty the Warrens',
  'Mind\'s Desire',
  'Brain Freeze',
  'Flusterstorm',
  'Gifts Ungiven',
  'Past in Flames',
  'Yawgmoth\'s Will',
  'Lion\'s Eye Diamond',
  'Lotus Petal',
  'Dark Ritual',
  'Cabal Ritual',
  'Desperate Ritual',
  'Pyretic Ritual',
  'Seething Song',
  'Manamorphose',
  'Gitaxian Probe',

  // Dredge
  'Life from the Loam',
  'Stinkweed Imp',
  'Golgari Grave-Troll',
  'Golgari Thug',
  'Darkblast',
  'Cathartic Reunion',
  'Faithless Looting',
  'Creeping Chill',
  'Narcomoeba',
  'Prized Amalgam',
  'Bloodghast',
  'Ichorid',
  'Bridge from Below',

  // Lands Matter
  'Azusa, Lost but Seeking',
  'Tireless Tracker',
  'Omnath, Locus of Rage',
  'Omnath, Locus of the Roil',
  'Omnath, Locus of Creation',
  'Tatyova, Benthic Druid',
  'The Gitrog Monster',
  'Titania, Protector of Argoth',
  'Ramunap Excavator',
  'Crucible of Worlds',
  'Life from the Loam',
  'Scapeshift',
  'Field of the Dead',
  'Valakut, the Molten Pinnacle',

  // Counterspells
  'Force of Will',
  'Force of Negation',
  'Pact of Negation',
  'Mana Drain',
  'Counterspell',
  'Arcane Denial',
  'Swan Song',
  'Dispel',
  'Spell Pierce',
  'Flusterstorm',
  'Mystical Dispute',
  'Negate',
  'Dovin\'s Veto',
  'Absorb',
  'Cryptic Command',
  'Dissolve',
  'Forbid',
  'Memory Lapse',
  'Remand',
  'Mana Leak',

  // Mill
  'Mesmeric Orb',
  'Hedron Crab',
  'Ruin Crab',
  'Glimpse the Unthinkable',
  'Archive Trap',
  'Mind Funeral',
  'Traumatize',
  'Phenax, God of Deception',
  'Bruvac the Grandiloquent',
  'Fraying Sanity',

  // Burn
  'Lightning Bolt',
  'Lava Spike',
  'Rift Bolt',
  'Skullcrack',
  'Boros Charm',
  'Atarka\'s Command',
  'Lightning Helix',
  'Searing Blaze',
  'Monastery Swiftspear',
  'Eidolon of the Great Revel',
  'Goblin Guide',

  // Additional Modern Staples
  'Blood Moon',
  'Chalice of the Void',
  'Trinisphere',
  'Ensnaring Bridge',
  'Pithing Needle',
  'Torpor Orb',
  'Damping Sphere',
  'Stony Silence',
  'Leyline of Sanctity',
  'Leyline of the Void',
  'Leyline of Anticipation',

  // Additional Legacy Staples
  'Brainstorm',
  'Force of Will',
  'Swords to Plowshares',
  'Lightning Bolt',
  'Wasteland',
  'Dark Ritual',
  'Show and Tell',
  'Natural Order',
  'Griselbrand',
];

/**
 * Get the popular cards list with a specified limit
 */
export const getPopularCardsList = (limit: number = 1000): string[] => {
  return POPULAR_CARDS.slice(0, Math.min(limit, POPULAR_CARDS.length));
};
