FROM node:20
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.26.2 --activate

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY packages/shared/package.json ./packages/shared/
COPY packages/core/package.json ./packages/core/
COPY apps/auth/package.json ./apps/auth/

RUN pnpm install --frozen-lockfile

COPY packages/shared ./packages/shared
COPY packages/core ./packages/core
COPY apps/auth ./apps/auth
COPY tsconfig.json nx.json ./

RUN pnpm nx build auth

WORKDIR /app/apps/auth

EXPOSE 5002

CMD ["pnpm", "dev"]
