import type { PriceLookupState } from '@/hooks/useListPrices';
import type { ListHistoryEntry } from '@/hooks/useListEditor';
import type { ListCardEntry } from '@/api/lists';
import type { SortBy } from '../SortByMenu';
import type { ListRefreshItem } from '@/api/lists';

export type CardListPanelProps = {
  entries: ListCardEntry[];
  selectedName: string | null;
  onSelect: (name: string) => void;
  sortBy: SortBy;
  onSortByChange: (sortBy: SortBy) => void;
  results: Record<string, PriceLookupState>;
  inCartByName: (name: string) => boolean;
  cartPriceByName: (name: string) => number | undefined;
  history: ListHistoryEntry[];
  existingNames: string[];
  onAddCard: (name: string) => void;
  onRemoveCard: (name: string) => void;
  onUndoHistory: (id: string) => void;
  onAddBestCards: () => void;
  isAddingBestCards: boolean;
  canAddBestCards: boolean;
  loadedPriceCount: number;
  totalPriceCount: number;
  hasMorePrices: boolean;
  isLoadingMorePrices: boolean;
  onLoadMorePrices: () => void;
  isRefreshing: boolean;
  refreshProgress: number;
  refreshItems: ListRefreshItem[];
  onRefresh: () => void;
  onDismissRefreshResults: () => void;
};
